# Generated by Django 4.1.13 on 2023-12-27 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="meal",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
